services: 
    api:
        build: ./api
        image: api_image
        container_name: api_container
        ports:
            - "4000:4000"
        volumes: 
            - ./api:/app
            - /app/node_modules

    my-app:
        build: ./my-app
        image: my-app_image
        container_name: my-app_container
        ports:
            - "5173:5173"
        volumes: 
            - ./my-app:/my-app
            - /my-app/node_modules
      